name: IUSafe CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Project
        run: ./mvnw compile

  unit-test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4

      - name: Run Test
        run: ./mvnw test

